name: Code Check

on:
  pull_request:
    branches: ["*"]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [1.24.3]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Format code
        run: go fmt ./...

  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [1.24.3]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  sec:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [1.24.3]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      # - name: Sec
      #   uses: securego/gosec@master
      #   with:
      #     args: ./...

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Sec
        run: gosec ./...

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [1.24.3]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: |
          go build -o bin/go-orchestrator cmd/go-orchestrator/main.go
